In [4]:
import torch


# batch flattening
batch = 16

torch.rand(batch, 2, 5).view((batch, -1))

tensor([[0.1324, 0.3776, 0.9952, 0.2225, 0.6883, 0.7313, 0.8635, 0.8535, 0.2802,
         0.8259],
        [0.9777, 0.7282, 0.2851, 0.8629, 0.6863, 0.8143, 0.1612, 0.2902, 0.9240,
         0.4343],
        [0.5273, 0.8471, 0.2330, 0.7607, 0.9463, 0.3622, 0.7719, 0.1110, 0.9643,
         0.0217],
        [0.7725, 0.3826, 0.8633, 0.1631, 0.5176, 0.4389, 0.1549, 0.8595, 0.5593,
         0.4006],
        [0.7384, 0.9566, 0.5203, 0.2204, 0.8526, 0.7440, 0.5261, 0.7483, 0.8609,
         0.5595],
        [0.5030, 0.1810, 0.0326, 0.8091, 0.7158, 0.4160, 0.9972, 0.3062, 0.0083,
         0.3463],
        [0.9251, 0.9573, 0.2596, 0.2097, 0.0825, 0.5259, 0.6853, 0.9977, 0.7071,
         0.2107],
        [0.3733, 0.3814, 0.4579, 0.4099, 0.7417, 0.7744, 0.6128, 0.1689, 0.2937,
         0.0917],
        [0.8324, 0.4787, 0.9888, 0.6039, 0.1091, 0.3131, 0.3936, 0.0629, 0.7879,
         0.5870],
        [0.2105, 0.5958, 0.2579, 0.0648, 0.4019, 0.3262, 0.2301, 0.8004, 0.5640,
         0.7757],
        [0

In [8]:
tensor = torch.rand(size=(10,10))
tensor

tensor([[0.0622, 0.8211, 0.3919, 0.9842, 0.7797, 0.8888, 0.9157, 0.8690, 0.5900,
         0.4515],
        [0.0339, 0.4481, 0.3670, 0.7640, 0.2819, 0.1707, 0.1722, 0.0517, 0.1103,
         0.1821],
        [0.7398, 0.2416, 0.4764, 0.7784, 0.5890, 0.0243, 0.8396, 0.4625, 0.7254,
         0.2836],
        [0.8690, 0.8954, 0.5303, 0.8514, 0.1135, 0.9255, 0.1850, 0.9618, 0.5321,
         0.6918],
        [0.7173, 0.3214, 0.4934, 0.2958, 0.1741, 0.2706, 0.6667, 0.2751, 0.4923,
         0.8545],
        [0.3135, 0.5511, 0.8876, 0.3729, 0.5410, 0.2430, 0.6492, 0.8484, 0.5360,
         0.6536],
        [0.9886, 0.1497, 0.4395, 0.0331, 0.4220, 0.3430, 0.9705, 0.2178, 0.8278,
         0.2341],
        [0.4387, 0.4373, 0.5444, 0.1547, 0.0630, 0.5236, 0.4727, 0.0258, 0.1863,
         0.1236],
        [0.8258, 0.4758, 0.5571, 0.5928, 0.9868, 0.5365, 0.1074, 0.1484, 0.5362,
         0.2434],
        [0.3872, 0.5671, 0.5699, 0.7265, 0.4807, 0.6558, 0.8881, 0.2521, 0.2745,
         0.0178]])

In [12]:
tensor.reshape(4,25)

tensor([[0.0622, 0.8211, 0.3919, 0.9842, 0.7797, 0.8888, 0.9157, 0.8690, 0.5900,
         0.4515, 0.0339, 0.4481, 0.3670, 0.7640, 0.2819, 0.1707, 0.1722, 0.0517,
         0.1103, 0.1821, 0.7398, 0.2416, 0.4764, 0.7784, 0.5890],
        [0.0243, 0.8396, 0.4625, 0.7254, 0.2836, 0.8690, 0.8954, 0.5303, 0.8514,
         0.1135, 0.9255, 0.1850, 0.9618, 0.5321, 0.6918, 0.7173, 0.3214, 0.4934,
         0.2958, 0.1741, 0.2706, 0.6667, 0.2751, 0.4923, 0.8545],
        [0.3135, 0.5511, 0.8876, 0.3729, 0.5410, 0.2430, 0.6492, 0.8484, 0.5360,
         0.6536, 0.9886, 0.1497, 0.4395, 0.0331, 0.4220, 0.3430, 0.9705, 0.2178,
         0.8278, 0.2341, 0.4387, 0.4373, 0.5444, 0.1547, 0.0630],
        [0.5236, 0.4727, 0.0258, 0.1863, 0.1236, 0.8258, 0.4758, 0.5571, 0.5928,
         0.9868, 0.5365, 0.1074, 0.1484, 0.5362, 0.2434, 0.3872, 0.5671, 0.5699,
         0.7265, 0.4807, 0.6558, 0.8881, 0.2521, 0.2745, 0.0178]])

In [13]:
tensor[2, 3]

tensor(0.7784)

In [14]:
tensor[:, 0:-1:2]

tensor([[0.0622, 0.3919, 0.7797, 0.9157, 0.5900],
        [0.0339, 0.3670, 0.2819, 0.1722, 0.1103],
        [0.7398, 0.4764, 0.5890, 0.8396, 0.7254],
        [0.8690, 0.5303, 0.1135, 0.1850, 0.5321],
        [0.7173, 0.4934, 0.1741, 0.6667, 0.4923],
        [0.3135, 0.8876, 0.5410, 0.6492, 0.5360],
        [0.9886, 0.4395, 0.4220, 0.9705, 0.8278],
        [0.4387, 0.5444, 0.0630, 0.4727, 0.1863],
        [0.8258, 0.5571, 0.9868, 0.1074, 0.5362],
        [0.3872, 0.5699, 0.4807, 0.8881, 0.2745]])