In [1]:
import torch

In [2]:
torch.__version__

'1.12.1+cu102'

### Tensor defining and parameters

In [3]:
tensor_obj = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(tensor_obj)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
tensor_obj.dtype

torch.int64

In [5]:
tensor_obj.requires_grad

False

In [6]:
tensor_obj.shape

torch.Size([2, 3])

In [7]:
tensor_obj.device

device(type='cpu')

In [8]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [9]:
tensor_obj2 = torch.tensor([[11, 22, 33],[111, 222, 333]], dtype= torch.float, requires_grad=True, device=device)
tensor_obj2

tensor([[ 11.,  22.,  33.],
        [111., 222., 333.]], requires_grad=True)

In [10]:
tensor_obj2.requires_grad

True

In [11]:
tensor_obj2.device

device(type='cpu')

In [12]:
tensor_obj2.dtype

torch.float32

### Tensor functions.

In [13]:
x_zeros = torch.zeros(size=(4, 5))
x_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [14]:
x_ones = torch.ones(size=(5,6))
x_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [15]:
x_rand = torch.rand(size=(4, 4))
x_rand

tensor([[0.1420, 0.7915, 0.8751, 0.8542],
        [0.5966, 0.2852, 0.4810, 0.2949],
        [0.6430, 0.3013, 0.1340, 0.1060],
        [0.6452, 0.4105, 0.9134, 0.4922]])

In [16]:
x_empty = torch.empty(size=(3, 3))
x_empty

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45]])

In [17]:
x_identity = torch.eye(n=6)
x_identity

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [18]:
# in torch.arange  steps acts as a gap between two numbers.
x_range = torch.arange(1, 2.5, 0.5)
x_range 

tensor([1.0000, 1.5000, 2.0000])

In [19]:
# in linspace steps acts as number of numbers to be generated.

x_linspace = torch.linspace(1, 2, 10)
x_linspace

tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])

In [20]:
#  getting normally distributed tensor

x_normal = torch.rand(size=(4,5)).normal_(mean=0, std=1)
print(x_normal, x_normal.dtype)

tensor([[-1.6699, -0.2487, -1.1692, -0.8016,  0.9538],
        [ 0.2599,  2.1442, -0.0531,  2.0129, -0.8903],
        [ 0.5768,  0.5186, -0.3490,  1.0404,  0.3745],
        [-0.7804,  0.9050, -1.9377,  0.2360, -0.9946]]) torch.float32


In [21]:
# getting a uniform distributed tensor

x_uniform = torch.rand(size=(5, 6)).uniform_()
x_uniform

tensor([[0.3225, 0.9325, 0.5993, 0.0784, 0.4777, 0.4077],
        [0.1427, 0.5537, 0.9127, 0.5203, 0.7212, 0.0527],
        [0.1508, 0.3808, 0.4716, 0.4713, 0.7109, 0.7691],
        [0.9372, 0.2313, 0.0272, 0.1984, 0.7430, 0.8620],
        [0.2058, 0.1011, 0.5242, 0.1961, 0.5057, 0.3044]])

x_diagonal = torch.diag(torch.rand(5).normal_(mean=0, std=1))
x_diagonal

### Tensor conversions

In [22]:
y  = torch.rand(size=(4,4)).normal_(mean=0, std=1)
print(y, y.dtype)

tensor([[ 0.8352,  1.5845,  0.2173, -0.0249],
        [-2.5125, -1.3884, -0.9418,  0.4847],
        [ 2.0778,  1.8732,  0.5823,  0.1550],
        [ 1.0792, -1.1489, -0.4715,  0.7479]]) torch.float32


In [23]:
y_bool = y.bool()
y_bool

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [24]:
y_int = y.int()
y_int

tensor([[ 0,  1,  0,  0],
        [-2, -1,  0,  0],
        [ 2,  1,  0,  0],
        [ 1, -1,  0,  0]], dtype=torch.int32)

In [25]:
y_short = y.short()
y_short

tensor([[ 0,  1,  0,  0],
        [-2, -1,  0,  0],
        [ 2,  1,  0,  0],
        [ 1, -1,  0,  0]], dtype=torch.int16)

In [26]:
y_long = y.long()
y_long.dtype

torch.int64

In [27]:
y_half = y.half()
y_half

tensor([[ 0.8354,  1.5840,  0.2173, -0.0249],
        [-2.5117, -1.3887, -0.9419,  0.4846],
        [ 2.0781,  1.8730,  0.5820,  0.1550],
        [ 1.0791, -1.1484, -0.4714,  0.7480]], dtype=torch.float16)

In [28]:
y_float = y.float()
y_float

tensor([[ 0.8352,  1.5845,  0.2173, -0.0249],
        [-2.5125, -1.3884, -0.9418,  0.4847],
        [ 2.0778,  1.8732,  0.5823,  0.1550],
        [ 1.0792, -1.1489, -0.4715,  0.7479]])

In [29]:
y_double = y.double()
y_double

tensor([[ 0.8352,  1.5845,  0.2173, -0.0249],
        [-2.5125, -1.3884, -0.9418,  0.4847],
        [ 2.0778,  1.8732,  0.5823,  0.1550],
        [ 1.0792, -1.1489, -0.4715,  0.7479]], dtype=torch.float64)

### numpy conversion

In [30]:
import numpy as np

x_random = np.random.rand(4, 4)
x_random

array([[0.25957116, 0.49378918, 0.32646111, 0.39523475],
       [0.74855788, 0.24326969, 0.9007454 , 0.67865186],
       [0.20616847, 0.33315014, 0.37248415, 0.1044693 ],
       [0.70279886, 0.20952983, 0.49071907, 0.06565509]])

In [31]:
x_tensor_frm_np = torch.from_numpy(x_random)
x_tensor_frm_np

tensor([[0.2596, 0.4938, 0.3265, 0.3952],
        [0.7486, 0.2433, 0.9007, 0.6787],
        [0.2062, 0.3332, 0.3725, 0.1045],
        [0.7028, 0.2095, 0.4907, 0.0657]], dtype=torch.float64)

In [32]:
# from tensor to numpy

x_numpy_from_tensor = x_tensor_frm_np.numpy()
x_numpy_from_tensor

array([[0.25957116, 0.49378918, 0.32646111, 0.39523475],
       [0.74855788, 0.24326969, 0.9007454 , 0.67865186],
       [0.20616847, 0.33315014, 0.37248415, 0.1044693 ],
       [0.70279886, 0.20952983, 0.49071907, 0.06565509]])

1. arange(gap), linspace(no .of values)
2. ones, zeros, rand, eye, empty, rand(s).normal_(mean, std), rand.uniform_()
3. conversions ==> integer(short, int, float)  float(half, float, double), bool
4. torch.from_numpy(numpy_array), tensor.numpy()
5. dtype, shape, device, required_grad

In [ ]:
# this is revision of pytorch
#The more you practise the more you will remember
