In [1]:
import torch as tc

x = tc.ones(size=(3,5))
y = tc.ones(size=(3,5))
print(x.shape, y.shape)

torch.Size([3, 5]) torch.Size([3, 5])


In [2]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [3]:
y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [4]:
z = x+y
z

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [5]:
z = x-y
z

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
z = x/y
z

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [7]:
z.dtype

torch.float32

In [8]:
z

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
m = tc.rand(size=(3, 5))
m

tensor([[0.0377, 0.5159, 0.6429, 0.7913, 0.5554],
        [0.4108, 0.9623, 0.1639, 0.2138, 0.6218],
        [0.4568, 0.5335, 0.8428, 0.8375, 0.9337]])

In [10]:
m=m-m+3
m

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [11]:
m.pow(2)

tensor([[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]])

In [12]:
m**2

tensor([[9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9.]])

In [13]:
n = tc.rand(size=(4,4))
n>0.3

tensor([[False,  True,  True,  True],
        [ True, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True, False,  True]])

In [14]:
# This is mathematical multiplication.

A = tc.ones(size=(4,4))* 3
B = tc.ones(size=(4,4))* 2

C = A@B
C

tensor([[24., 24., 24., 24.],
        [24., 24., 24., 24.],
        [24., 24., 24., 24.],
        [24., 24., 24., 24.]])

In [15]:
A.matmul(B)

tensor([[24., 24., 24., 24.],
        [24., 24., 24., 24.],
        [24., 24., 24., 24.],
        [24., 24., 24., 24.]])

In [16]:
k = tc.ones(size=(3,3))
print(k)
k.matrix_exp()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[7.3618, 6.3618, 6.3618],
        [6.3618, 7.3618, 6.3618],
        [6.3618, 6.3618, 7.3618]])

In [17]:
# dot product takes one dimensional data
x = tc.arange(5)
y = tc.arange(5, 10)
print(x, y)
tc.dot(x, y)

tensor([0, 1, 2, 3, 4]) tensor([5, 6, 7, 8, 9])


tensor(80)

### Broadcasting

In [18]:
z.add_(3)

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [19]:
z

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [20]:
z+1

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])

In [21]:
z-3

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [22]:
z*0.75

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [23]:
z/2

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

# maths operations of Different size tensors

In [24]:
m = tc.rand(size = (3, 5))
n = tc.rand(size = (1,5))
print(m.shape, n.shape)

torch.Size([3, 5]) torch.Size([1, 5])


In [25]:
m

tensor([[0.6045, 0.9191, 0.5632, 0.3326, 0.8231],
        [0.4156, 0.6080, 0.9153, 0.1058, 0.8442],
        [0.4495, 0.6030, 0.6666, 0.8988, 0.1987]])

In [26]:
n

tensor([[0.0662, 0.9066, 0.8877, 0.0194, 0.8271]])

In [27]:
m-n

tensor([[ 0.5382,  0.0125, -0.3244,  0.3132, -0.0039],
        [ 0.3494, -0.2987,  0.0276,  0.0864,  0.0171],
        [ 0.3832, -0.3037, -0.2210,  0.8794, -0.6284]])

In [28]:
m+n

tensor([[0.6707, 1.8257, 1.4509, 0.3520, 1.6502],
        [0.4819, 1.5146, 1.8030, 0.1252, 1.6713],
        [0.5157, 1.5096, 1.5543, 0.9182, 1.0258]])

In [29]:
m*n

tensor([[0.0400, 0.8333, 0.5000, 0.0064, 0.6808],
        [0.0275, 0.5512, 0.8125, 0.0021, 0.6982],
        [0.0298, 0.5466, 0.5917, 0.0174, 0.1643]])

In [30]:
m/n

tensor([[ 9.1252,  1.0138,  0.6345, 17.1600,  0.9952],
        [ 6.2746,  0.6706,  1.0311,  5.4587,  1.0207],
        [ 6.7855,  0.6651,  0.7510, 46.3729,  0.2402]])

In [31]:
l = tc.rand(size=(3,1))

In [32]:
l

tensor([[0.1163],
        [0.4783],
        [0.2927]])

In [33]:
l+m

tensor([[0.7208, 1.0354, 0.6795, 0.4489, 0.9394],
        [0.8940, 1.0863, 1.3936, 0.5841, 1.3225],
        [0.7421, 0.8956, 0.9593, 1.1914, 0.4914]])

In [34]:
l-n

tensor([[ 0.0500, -0.7903, -0.7714,  0.0969, -0.7108],
        [ 0.4121, -0.4283, -0.4093,  0.4590, -0.3487],
        [ 0.2264, -0.6140, -0.5950,  0.2733, -0.5344]])

In [35]:
l*m

tensor([[0.0703, 0.1069, 0.0655, 0.0387, 0.0957],
        [0.1988, 0.2908, 0.4378, 0.0506, 0.4038],
        [0.1315, 0.1765, 0.1951, 0.2630, 0.0582]])

In [36]:
l/m

tensor([[0.1924, 0.1265, 0.2065, 0.3496, 0.1413],
        [1.1508, 0.7868, 0.5226, 4.5212, 0.5666],
        [0.6511, 0.4854, 0.4390, 0.3256, 1.4728]])

In [37]:
tc.sum(m)

tensor(8.9480)

In [38]:
tc.sum(m, dim=0)

tensor([1.4696, 2.1300, 2.1452, 1.3372, 1.8660])

In [39]:
tc.max(m)

tensor(0.9191)

In [40]:
tc.max(m, dim =1)

torch.return_types.max(
values=tensor([0.9191, 0.9153, 0.8988]),
indices=tensor([1, 2, 3]))

In [41]:
tc.min(m, dim=0)

torch.return_types.min(
values=tensor([0.4156, 0.6030, 0.5632, 0.1058, 0.1987]),
indices=tensor([1, 2, 0, 1, 2]))

In [42]:
tc.sort(m)

torch.return_types.sort(
values=tensor([[0.3326, 0.5632, 0.6045, 0.8231, 0.9191],
        [0.1058, 0.4156, 0.6080, 0.8442, 0.9153],
        [0.1987, 0.4495, 0.6030, 0.6666, 0.8988]]),
indices=tensor([[3, 2, 0, 4, 1],
        [3, 0, 1, 4, 2],
        [4, 0, 1, 2, 3]]))

In [43]:
tc.abs(-m)

tensor([[0.6045, 0.9191, 0.5632, 0.3326, 0.8231],
        [0.4156, 0.6080, 0.9153, 0.1058, 0.8442],
        [0.4495, 0.6030, 0.6666, 0.8988, 0.1987]])

In [44]:
tc.argmax(m)

tensor(1)

In [45]:
tc.argmin(m)

tensor(8)

In [46]:
tc.mean(m, dim=0)

tensor([0.4899, 0.7100, 0.7151, 0.4457, 0.6220])

In [47]:
tc.eq(m,n)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [48]:
tc.clamp(m,min=0.3)

tensor([[0.6045, 0.9191, 0.5632, 0.3326, 0.8231],
        [0.4156, 0.6080, 0.9153, 0.3000, 0.8442],
        [0.4495, 0.6030, 0.6666, 0.8988, 0.3000]])

1. if Two tensor
        a. same size:
             same indexed elements of same rows and columns are multiplied.
        b. same column size((3, 4) (1, 4):
             same indexed rows are multiplied with all other elements Row wise.
        c. same row size ((3, 4)  (3, 1)):
             same indexed columns are multiplied with all other elements column wise.
x+y, x-y, x*y, x/y, 

x@y. and x.matmul(y) ==> mathematical multiplication

torch.dot(x, y) x, y should be single dimensional. ==> single value comes.

x.pow(n) all the elements in the tensor will be rised to the power n.

x.matrix_exp()  ==> all the elements will undero exponenetial calculation.

Broatcasting: 
Here scaler is multiplied to tensor.
 x+1, x-2, x*3, x/5, x is a tensor.
 
 
 tensor function of maths.
 dim = 0 for row wise
 dim = 1 for column wise.
 
 torch.sum(x, dim)
 torch.min(x, dim)
 torch.max(x, dim)
 torch.argmax(x,dim) ==> will give index.
 torch.argmin(x, dim) ==> will give index.
 torch.mean(x, dim ) 
 torch.eq(x, y) ==> returns boolea value.
 torch.clamp(tensor, min=val) will replace the min val mentioned which are less than that value.
 torch.sort(, )
 torch.abs()
